<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-Q8UQAUDS" ignored="5" name="Default test(failed)" tests="2" failures="2" timestamp="2023-05-19T08:27:45 IST" time="0.135" errors="0">
  <testcase name="Test3" time="0.022" classname="testNG.Run_failed_test">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNG.Run_failed_test.Test3(Run_failed_test.java:37)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase name="Test5" time="0.002" classname="testNG.Run_failed_test">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNG.Run_failed_test.Test5(Run_failed_test.java:53)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test5 -->
  <testcase name="Test4" time="0.0" classname="testNG.Run_failed_test">
    <ignored/>
  </testcase> <!-- Test4 -->
  <testcase name="Test1" time="0.0" classname="testNG.Run_failed_test">
    <ignored/>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.0" classname="testNG.Run_failed_test">
    <ignored/>
  </testcase> <!-- Test2 -->
  <testcase name="Test7" time="0.0" classname="testNG.Run_failed_test">
    <ignored/>
  </testcase> <!-- Test7 -->
  <testcase name="Test6" time="0.0" classname="testNG.Run_failed_test">
    <ignored/>
  </testcase> <!-- Test6 -->
</testsuite> <!-- Default test(failed) -->
